spring:
   datasource:
      url: ${DATABASE_URI}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
   jpa:
      show-sql: false
      hibernate:
         ddl-auto: none
      database-platform: org.hibernate.dialect.MariaDBDialect
   servlet:
      multipart:
        enabled: true
        location: ${java.io.tmpdir}    
server:
   error:
      include-stacktrace: always
curation:
   pph-service:
      xsd_cache: ${CURATION_DIRECTORY}/xsd_cache
      restApi: "https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/1.x/profiles"
      query: "?registrySpace=published&status=production&status=development&&status=deprecated"
   ccr-service:
      restApi: "https://openskos.meertens.knaw.nl/ccr/api/find-concepts"
      query: "?q=status:[*%20TO%20*]&fl=status,uri,prefLabel@en&format=json&rows=5000"
   facets: 
      - languageCode
      - collection
      - resourceClass
      - modality
      - format
      - keywords
      - genre
      - subject
      - country
      - organisation
      - name
      - description
      - license
      - availability
   clientUsername: curation
   directory:
      home: ${CURATION_DIRECTORY}
      dataRoot: ${CURATION_DIRECTORY}/data
      in: 
      - ${CURATION_DIRECTORY}/data/clarin/results/cmdi
      out: ${CURATION_DIRECTORY}/public
   max_file_size: 100000
   threadPoolSize: ${THREAD_POOL_SIZE:10}
   mode: collection
   doc-url: "https://raw.githubusercontent.com/clarin-eric/cereal/main/curation-dashboard/markdown"         
logging:
   level:
      root: ERROR         