logging:
   file: 
      name: ${APPLICATION_HOME_DIRECTORY}/logs/curation-web.log
      logback:
         rollingpolicy:
            max-file-size: 10MB
   level:
      root: ERROR 
spring:
   datasource:
      url: ${DATABASE_URI}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
   jpa:
      show-sql: false
      hibernate:
         ddl-auto: none
      database-platform: org.hibernate.dialect.MariaDBDialect
   servlet:
      multipart:
        enabled: true
        location: ${java.io.tmpdir} 
   mvc:
      async:
         request-timeout: 3600000        
server:
   ssl:
      key-store-type: jks
      key-store: /cert/server.jks
      key-store-password: password
      key-alias: selfsigned
      enabled: true
   port: 8443  
curation:
   pph-service:
      restApi: "https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/1.x/profiles"
      query: "?registrySpace=published&status=production&status=development&&status=deprecated"
   ccr-service:
      ccr-cache: ${APPLICATION_HOME_DIRECTORY}/ccr_cache
      restApi: "https://vocabularies.clarin.eu/clavas/rest/v1/data"
      query: "?uri=${conceptURI}"
   cr-service:
      xsd_cache: ${APPLICATION_HOME_DIRECTORY}/xsd_cache
   directory:
      home: ${APPLICATION_HOME_DIRECTORY}
      dataRoot: ${APPLICATION_HOME_DIRECTORY}/data
      in: >
         ${APPLICATION_HOME_DIRECTORY}/data/clarin/results/cmdi
      out: ${APPLICATION_HOME_DIRECTORY}/public
      share: /share
   facets: 
      - languageCode
      - collection
      - resourceClass
      - modality
      - format
      - keywords
      - genre
      - subject
      - country
      - organisation
      - name
      - description
      - license
      - availability
      - temporalCoverage
   clientUsername: curation   
   max_file_size: 100000
   threadpoolSize: ${THREADPOOL_SIZE:10}
   mode: instance
   doc-url: "https://raw.githubusercontent.com/clarin-eric/cereal/main/curation-dashboard/markdown"
   vlo_config_location: "${VLO_CONFIG_LOCATION}"      
       