logging:
   level:
      root: DEBUG
spring:
   datasource:
      url: ${DATABASE_URI}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: none
      database-platform: org.hibernate.dialect.MariaDBDialect
   sql:
      init:
         mode: always    
   servlet:
      multipart:
        enabled: true
        location: ${java.io.tmpdir}  
curation:
   pph-service:
      xsd_cache: /tmp/curation/xsd_cache
      restApi: "https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/1.x/profiles"
      query: "?registrySpace=published&status=production&status=development&&status=deprecated"
   ccr-service:
      restApi: "https://openskos.meertens.knaw.nl/ccr/api/find-concepts"
      query: "?q=status:[*%20TO%20*]&fl=status,uri,prefLabel@en&format=json&rows=5000"   
   mode: collection
   directory:
      home: /app/curation
      dataRoot: /data/results/cmdi
      in: /data/results/cmdi/Language_Archive_Cologne
      out: /data/curation/public
   facets: 
      - languageCode
      - collection
      - resourceClass
      - modality
      - format
      - keywords
      - genre
      - subject
      - country
      - organisation
      - name
      - description
      - license
      - availability
   thread_pool_size: 10
   max_file_size: 100000
   base_url:
   doc_url:
   clientUsername: curation 