logging:
   file: 
      name: ${APPLICATION_HOME_DIRECTORY}/logs/curation-app.log
      logback:
         rollingpolicy:
            max-file-size: 10MB
   level:
      root: ERROR
      eu.clarin.cmdi.curation.app.CurationApp: INFO
spring:
   datasource:
      url: ${DATABASE_URI}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
   jpa:
      show-sql: false
      hibernate:
         ddl-auto: none
      database-platform: org.hibernate.dialect.MariaDBDialect
   sql:
      init:
         mode: always    
   servlet:
      multipart:
        enabled: true
        location: ${java.io.tmpdir}  
curation:
   pph-service:
      xsd_cache: ${java.io.tmpdir}/curation/xsd_cache
      restApi: "https://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/1.x/profiles"
      query: "?registrySpace=published&status=production&status=development&&status=deprecated"
   ccr-service:
      restApi: "https://openskos.meertens.knaw.nl/ccr/api/find-concepts"
      query: "?q=status:[*%20TO%20*]&fl=status,uri,prefLabel@en&format=json&rows=5000"   
   mode: all
   directory:
      home: ${APPLICATION_HOME_DIRECTORY}
      dataRoot: ${APPLICATION_HOME_DIRECTORY}/data
      in: 
      - ${APPLICATION_HOME_DIRECTORY}/data/clarin/results/cmdi
      out: ${APPLICATION_HOME_DIRECTORY}/public
   facets: 
      - languageCode
      - collection
      - resourceClass
      - modality
      - format
      - keywords
      - genre
      - subject
      - country
      - organisation
      - name
      - description
      - license
      - availability
   threadpool_size: ${THREADPOOL_SIZE:10}
   max_file_size: 100000
   base_url:
   doc_url:
   clientUsername: curation 
   link_deactivation_after: ${LINK_DEACTIVATION_AFTER:365}
   link_deletion_after: ${LINK_DELETION_AFTER:365}